# Uses Hydra Submitit Slurm launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 2880
nodes: 1
tasks_per_node: 1
cpus_per_task: 8
mem_gb: 64
partition: pierson
array_parallelism: 1
name: UAIR
additional_parameters:
  gres: "none"
  wckey: ""
srun_args:
  - --gres=none
  - --cpu-bind=none
setup:
  - export HYDRA_FULL_ERROR=1
  - source ~/.bashrc
  # Ensure conda is available in non-interactive batch shells
  - if [ -f /share/ju/matt/conda/etc/profile.d/conda.sh ]; then source /share/ju/matt/conda/etc/profile.d/conda.sh; fi
  - if [ -x /share/ju/matt/conda/bin/conda ]; then eval "$(/share/ju/matt/conda/bin/conda shell.bash hook)"; fi
  - conda activate /share/ju/matt/conda/cillm-lora || { [ -f /share/ju/matt/conda/cillm-lora/bin/activate ] && source /share/ju/matt/conda/cillm-lora/bin/activate; } || true
  # W&B is controlled via config; avoid forcing mode here
  - unset WANDB_DISABLED
  - if [ -n "$WANDB_MODE" ]; then export WANDB_MODE="$WANDB_MODE"; fi
  # propagate base URL if configured
  - if [ -n "$WANDB_BASE_URL" ]; then export WANDB_BASE_URL="$WANDB_BASE_URL"; fi
  - if [ -n "$WANDB_GROUP" ]; then export WANDB_GROUP="$WANDB_GROUP"; fi
  - export RULE_TUPLES_SILENT=1
  - export WANDB_SILENT=true
  # Ensure Ray detached actors are created in a stable namespace per run
  - export RAY_NAMESPACE=${oc.env:WANDB_GROUP,uair}
  - export TOKENIZERS_PARALLELISM=false
  # Disable SLURM CPU binding which can conflict with submitit's launch context
  - export SLURM_CPU_BIND=none
  # Respect SLURM CPU allocation for threaded libs (BLAS/OpenMP/numexpr/BLIS/veclib)
  - export OMP_NUM_THREADS=${oc.env:SLURM_CPUS_PER_TASK,8}
  - export MKL_NUM_THREADS=${oc.env:SLURM_CPUS_PER_TASK,8}
  - export OPENBLAS_NUM_THREADS=${oc.env:SLURM_CPUS_PER_TASK,8}
  - export NUMEXPR_MAX_THREADS=${oc.env:SLURM_CPUS_PER_TASK,8}
  - export VECLIB_MAXIMUM_THREADS=${oc.env:SLURM_CPUS_PER_TASK,8}
  - export BLIS_NUM_THREADS=${oc.env:SLURM_CPUS_PER_TASK,8}
  # Avoid GPU-related exports in CPU-only parent
  - unset CUDA_VISIBLE_DEVICES
  - unset PYTORCH_CUDA_ALLOC_CONF
  - unset CUDA_LAUNCH_BLOCKING

