# Uses Hydra Submitit Slurm launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 480
nodes: 1
tasks_per_node: 1
cpus_per_task: 8
mem_gb: ${runtime.job_memory_gb}
partition: pierson
array_parallelism: 1
gpus_per_node: 2
name: UAIR
additional_parameters:
  gres: gpu:2
  wckey: ""
setup:
  - export HYDRA_FULL_ERROR=1
  - source ~/.bashrc
  # Ensure conda is available in non-interactive batch shells
  - test -f /share/ju/matt/conda/etc/profile.d/conda.sh && source /share/ju/matt/conda/etc/profile.d/conda.sh || true
  - conda activate /share/ju/matt/conda/cillm-lora || source activate /share/ju/matt/conda/cillm-lora
  - unset WANDB_DISABLED
  - export RULE_TUPLES_SILENT=1
  - export WANDB_SILENT=true
  - export VLLM_WORKER_MULTIPROC_METHOD=spawn
  - export VLLM_USE_V1=1
  - export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:64,expandable_segments:True
  - export CUDA_LAUNCH_BLOCKING=0
  - export TOKENIZERS_PARALLELISM=false
  - export CUDA_VISIBLE_DEVICES=0,1
  # Fallback: disable CPU bind via env if launcher ignores srun_args
  - export SLURM_CPU_BIND=none

