# Top-level Hydra config for E_CI-rule-tuples

defaults:
  - data: flattened_rules
  - prompt: classify
  - prompt@prompt_decompose: decompose
  - model: vllm_qwen3-30b
  - _self_

experiment:
  name: E_CI_rule_tuples

runtime:
  stage: classify   # classify | decompose | pipeline
  debug: false
  sample_n: null
  output_csv: null
  use_llm_classify: false
  use_llm_decompose: false
  max_errored_blocks: 0
  guided_decoding_decompose: false
  streaming_io: false
  output_dir: null
  serialize_nested_json: true

sampling_params:
  seed: 777
  temperature: 0.0
  top_p: 1.0
  top_k: -1
  max_tokens: 2048

# Stage-specific sampling overrides
sampling_params_classify:
  max_tokens: 4
  detokenize: false
  guided_decoding:
    choice:
      - "YES"
      - "NO"

sampling_params_decompose:
  max_tokens: 1024
  detokenize: false

wandb:
  enabled: true
  name_prefix: null
  project: ${oc.env:WANDB_PROJECT,E_rule_tuples}
  entity: ${oc.env:WANDB_ENTITY,}


hydra:
  job:
    name: ${experiment.name}
  run:
    dir: ${oc.env:HYDRA_RUN_DIR,outputs}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${oc.env:HYDRA_SWEEP_DIR,multirun}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}


